### ISSUE TITLE
LaunchPad V0.15 doesn't think any MessageBridges are running

### ISSUE THREAD

**Issue by jcrouchley** [WirelessThings/WirelessThings-LaunchPad#22]
1. Start LaunchPad with MessageBridges running on the network
2. Observer that LaunchPad looks for MessageBridges and reports that it cannot find any
3. Start the ConfigurationWizard note that it finds the running MessageBridges

Confusing to user and should be fixed before 0.15 release.

**Comment by marcosamorim** [comment]
Already fixed.
