### ISSUE TITLE
Stop services from LaunchPad

### ISSUE THREAD

**Issue by marcosamorim** [WirelessThings/WirelessThings-LaunchPad#24]
If a service was started by the root (e.g autostart script), you can't stop it by LaunchPad, unless you start the LaunchPad using sudo.
Also, this also build the CSV log files be created by the root user.

**Comment by dpslwk** [comment]
Fixed stoping by #39??

**Comment by marcosamorim** [comment]
Fix the service part and recent changes on MessageBridge, sudo is required to start the service.
